config/routes.rb
Kremlin::Application.routes.draw do

  resources :note_categories
  resources :notes
  resources :people
  resources :competitors
  resources :schools

  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :project_entries
  resources :projects

  resources :users do
    resources :projects do
      resources :project_entries
    end
    resources :notes
    resources :note_categories
  end

  root to: "pages#home"

end

app/models/project_entry.rb
class ProjectEntry < ActiveRecord::Base
  belongs_to :project

  def duration
    ((finish - start)/1.minute).round
  end

end

app/controllers/project_entries_controller.rb
class ProjectEntriesController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  # GET /project_entries
  # GET /project_entries.json
  def index
    @project_entries = ProjectEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_entries }
    end
  end

  # GET /project_entries/1
  # GET /project_entries/1.json
  def show
    @project_entry = ProjectEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_entry }
    end
  end

  # GET /project_entries/new
  # GET /project_entries/new.json
  def new
    @project = Project.find(params[:project_id])
    @project_entry = ProjectEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_entry }
    end
  end

  # GET /project_entries/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @project_entry = ProjectEntry.find(params[:id])
  end

  # POST /project_entries
  # POST /project_entries.json
  def create
    @project = Project.find(params[:project_id])
    @project_entry = @project.project_entries.new(params[:project_entry])
    @project_entry.start = Time.now

    respond_to do |format|
      if @project_entry.save
        format.html { redirect_to @project, notice: 'Project entry was successfully created.' }
        format.json { render json: @project_entry, status: :created, location: @project_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @project_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_entries/1
  # PUT /project_entries/1.json
  def update
    @project = Project.find(params[:project_id])
    @project_entry = ProjectEntry.find(params[:id])

    respond_to do |format|
      if @project_entry.update_attributes(project_entry_params)
        format.html { redirect_to @project, notice: 'Project entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_entries/1
  # DELETE /project_entries/1.json
  def destroy
    @project_entry = ProjectEntry.find(params[:id])
    @project_entry.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private

  def project_entry_params
    params.require(:project_entry)
          .permit(:comment, :finish, :project_id, :start)
  end
end

app/helpers/project_entries_helper.rb
module ProjectEntriesHelper
end

app/views/project_entries/_form.html.erb
<%= form_for [current_user, @project, @project_entry] do |f| %>
  <% if @project_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_entry.errors.count, "error") %> prohibited this project_entry from being saved:</h2>

      <ul>
      <% @project_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, rows: 3 %>
  </div>
  <div class="field">
    <%= f.hidden_field :finish, class: "timepicker", value: "#{Time.now}" %>
  </div>
  <div class="actions nudge-down">
    <%= f.submit "Submit", class: "btn btn-red" %>
  </div>
<% end %>

app/views/project_entries/edit.html.erb
<div class="formcontainer">
	<h1>Update Project Entry</h1>
	<%= render 'form' %>
</div>

app/views/project_entries/index.html.erb
<h1>Listing project_entries</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Comment</th>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_entries.each do |project_entry| %>
  <tr>
    <td><%= project_entry.project_id %></td>
    <td><%= project_entry.comment %></td>
    <td><%= project_entry.start %></td>
    <td><%= project_entry.end %></td>
    <td><%= link_to 'Show', project_entry %></td>
    <td><%= link_to 'Edit', edit_project_entry_path(project_entry) %></td>
    <td><%= link_to 'Destroy', project_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project entry', new_project_entry_path %>

app/views/project_entries/new.html.erb
<h1>New project_entry</h1>
<%= render 'form' %>

app/views/project_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @project_entry.project_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @project_entry.comment %>
</p>

<p>
  <b>Start:</b>
  <%= @project_entry.start %>
</p>

<p>
  <b>End:</b>
  <%= @project_entry.end %>
</p>


<%= link_to 'Edit', edit_project_entry_path(@project_entry) %> |
<%= link_to 'Back', project_entries_path %>