config/routes.rb
Kremlin::Application.routes.draw do

  resources :note_categories
  resources :notes
  resources :people
  resources :competitors
  resources :schools

  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :project_entries
  resources :projects

  resources :users do
    resources :projects do
      resources :project_entries
    end
    resources :notes
    resources :note_categories
  end

  root to: "pages#home"

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :project_entries
  belongs_to :user

   validates :git_repo, presence: true
   validates :name, presence: true
   validates :color, presence: true
   validates :website, presence: true

  def hourly_rate_in_minutes
    hourly.to_f / 60
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @project_entries = ProjectEntry.find(:all)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @user = User.find(params[:user_id])
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @user = User.find(params[:user_id])
    @project = @user.projects.new(project_params)


    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @user, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project)
          .permit(:color, :git_repo, :name, :user_id, :website, :hourly)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@user, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Project Name" %>
  </div>
  <div class="field">
    <%= f.text_field :website, placeholder: "Website" %>
  </div>
  <div class="field">
    <%= f.text_field :git_repo, placeholder: "GitHub Repo" %>
  </div>
  <div class="field">
    <%= f.text_field :hourly, placeholder: "Hourly Rate" %>
  </div>
  <div class="field">
    <%= f.text_field :color, placeholder: "Color" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-red" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="formcontainer">
	<h1>Editing <%= @project.name %></h1>
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<center><%= link_to new_user_project_path(current_user), class: "btn btn-red btn-mini"  do %><i class="fa fa-plus fa-3x"></i><% end %></center><br>
<center>
    <% current_user.projects.each do |project| %>
        <div class="project-square <%= project.color %>">
          <%= link_to project.git_repo do %><i class="fa fa-github"></i><% end %>
          <%= link_to project.website do %><i class="fa fa-globe"></i><% end %>
          <%= link_to user_project_path(project.user, project) do %><h3><%= project.name %></h3><% end %>
        </div>
    <% end %>
</center>

app/views/projects/new.html.erb
<h1 class="text-center">New Project</h1>
<div class="formcontainer">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<h1 class="text-center"><%= @project.name %></h1>
<div class="text-center">
<%= link_to @project.website do %><i class="fa fa-globe fa-4x icon-session-action"></i> <% end %>
<%= link_to @project.git_repo do %><i class="fa fa-github fa-4x icon-session-action"></i> <% end %>
</div>
<br>
<center>
  <%= link_to user_project_project_entries_path(current_user, @project), :method => :post, class: "btn btn-mini btn-green" do %><i class="fa fa-plus fa-2x"></i><% end %>
</center>
<br>
<table class="table project-sessions-table kremlin-sortable">
  <thead>
    <tr>
      <th width="15%"><a href="#">Start</a></th>
      <th width="15%"><a href="#">Finish</a></th>
      <th width="10%"><a href="#">Date</a></th>
      <th>Comments</th>
    </tr>
  </thead>
  <% @project.project_entries.reverse.each do |entry| %>
    <tr>
      <td numerical-value="<%= entry.start.to_i %>"><%= entry.start.strftime("%A at  %l:%M%P") %></td>
      <td numerical-value="<%= entry.finish.to_i %>">
        <% if entry.finish.blank? %>
        <%= link_to edit_user_project_project_entry_path(current_user, @project, entry) do %><i class="fa fa-check-circle-o icon-session-action fa-2x"></i> <% end %>
        <% else %>
        <%= entry.finish.strftime("%A at  %l:%M%P") %>
        <% end %>
      </td>
      <td numerical-value="<%= entry.start.to_i %>"><%= entry.start.strftime("%-m/%d/%y") %></td>
      <td>
        <% if entry.finish.blank? %>
        <% else %>
        <b><%= number_to_currency(entry.duration * @project.hourly_rate_in_minutes, percision: 2) %></b> worth of work.<br>
        <%= entry.comment %>
        <%= link_to entry, method: :delete, data: { confirm: 'Are you sure?' } do %> <i class="fa fa-times-circle-o icon-session-action"></i> <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<div class="text-center">
  <%= link_to 'Edit Project', edit_user_project_path(current_user, @project), class: "btn btn-yellow btn-mini" %>
  <%= link_to 'Delete Project', user_project_path(current_user, @project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red btn-mini" %>
</div>