config/routes.rb
Kremlin::Application.routes.draw do

  resources :note_categories
  resources :notes
  resources :people
  resources :competitors
  resources :schools

  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :project_entries
  resources :projects

  resources :users do
    resources :projects do
      resources :project_entries
    end
    resources :notes
    resources :note_categories
  end

  root to: "pages#home"

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :competitor
  has_many :people
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  authorize_resource
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new
    @competitors = Competitor.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
    @competitors = Competitor.all
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private

  def school_params
    params.require(:school)
          .permit(:budget, :competitor_id, :facebook, :latitude, :longitude, :name, :newspaper, :private, :saf, :sga_facebook, :sga_twitter, :sga_website, :students, :twitter, :website, :wiki, :customer, :anchor_school)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "School Name" %>
  </div>
  <div class="field">
    <%= f.text_field :website, placeholder: "Website" %>
  </div>
  <div class="field">
    <%= f.text_field :facebook, placeholder: "Facebook" %>
  </div>
  <div class="field">
    <%= f.text_field :twitter, placeholder: "Twitter" %>
  </div>
  <div class="field">
    <%= f.text_field :wiki, placeholder: "Wikipedia" %>
  </div>
  <div class="field">
    <%= f.text_field :students, placeholder: "Number of Students" %>
  </div>
  <legend>Student Government</legend>
  <div class="field">
    <%= f.text_field :saf, placeholder: "Student Activity Fee" %>
  </div>
  <div class="field">
    <%= f.text_field :budget, placeholder: "SGA Budget" %>
  </div>
  <div class="field">
    <%= f.text_field :sga_website, placeholder: "SGA Website" %>
  </div>
  <div class="field">
    <%= f.text_field :sga_facebook, placeholder: "SGA Facebook" %>
  </div>
  <div class="field">
    <%= f.text_field :sga_twitter, placeholder: "SGA Twitter" %>
  </div>
  <div class="field">
    <%= f.text_field :newspaper, placeholder: "School Newspaper" %>
  </div>
  <legend>Competition?</legend>
  <div class="field">
    <%= collection_select(:school, :competitor_id, @competitors, :id, :name) %>
  </div>
  <legend>Location</legend>
  <div id="school_form_map"></div>
  <div class="field">
    <%= f.hidden_field :latitude, placeholder: "Latitude" %>
  </div>
  <div class="field">
    <%= f.hidden_field :longitude, placeholder: "Longitude" %>
  </div>
  <legend>Yes/No</legend>
  <div class="field">
    <%= f.label :customer, "Customer?" %>&nbsp;
    <%= f.check_box :customer %>
  </div>
  <div class="field">
    <%= f.label :private, "Private School?" %>&nbsp;
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :anchor_school, "Anchor School?" %>&nbsp;
    <%= f.check_box :anchor_school %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit "Submit", class: "btn btn-black" %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1 class="text-center">Editing <%= @school.name %></h1>
<div class="formcontainer">
	<%= render 'form' %>
</div>

app/views/schools/index.html.erb
<div id="school_index_map"></div>

<center><%= link_to new_school_path, class: "btn btn-red btn-mini" do %> <i class="fa fa-plus fa-3x"></i> <% end %></center><br>
<div class="school_cards_container">
  <% @schools.each do |school| %>
  <div class="school_card" data-latitude="<%= school.latitude %>" data-longitude="<%= school.longitude %>" data-name="<%= school.name %>">
    <h3 class="text-center"><%= link_to school.name, school %></h3>
    <div class="fa-row row">
      <div class="col-xs-4">
        <%= link_to school.website, target: "_blank" do %><i class="fa fa-globe"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to school.facebook, target: "_blank" do %><i class="fa fa-facebook"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to school.twitter, target: "_blank" do %><i class="fa fa-twitter"></i><% end %>
      </div>
    </div>
    <h4><%= number_with_delimiter(school.students) %> Students</h4>
    <center><%= link_to "Wiki", school.wiki, class: "btn btn-green btn-mini" %></center><br>
    <h3 class="text-center" id="sga">Student Government</h3>
    <div class="fa-row row">
      <div class="col-xs-4">
        <%= link_to school.sga_website, target: "_blank" do %><i class="fa fa-globe"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to school.sga_facebook, target: "_blank" do %><i class="fa fa-facebook"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to school.sga_twitter, target: "_blank" do %><i class="fa fa-twitter"></i><% end %>
      </div>
    </div>
    <h4><%= number_to_currency(school.budget, precision: 0) || "N/A" %></h4>
    <center><%= link_to "Paper", school.newspaper, class: "btn btn-mini btn-green" %></center>
    <div class="fa-row row">
      <div class="col-xs-4">
        <%= link_to school do %><i class="fa fa-bullseye"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to edit_school_path(school) do %><i class="fa fa-cog"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to school, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-times-circle-o"></i><% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/schools/new.html.erb
<h1 class="text-center">New School</h1>
<div class="formcontainer">
	<%= render 'form' %>
</div>
<br>

app/views/schools/show.html.erb
<h1 class="text-center"><%= @school.name %></h1>
<div class="container school_show_container">
  <h3 class="text-center">School</h3>
  <div class="fa-row row">
    <div class="col-xs-4">
      <%= link_to @school.website do %><i class="fa fa-globe"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to @school.facebook do %><i class="fa fa-facebook"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to @school.twitter do %><i class="fa fa-twitter"></i><% end %>
    </div>
  </div>
  <br>
  <center><%= link_to "Wiki", @school.wiki, class: "btn btn-green btn-mini" %></center>
  <br>
  <h4><b><%= number_with_delimiter(@school.students) %></b><br><small>Undergraduate Students</small></h4>
  <h4><b><%= number_to_currency(@school.saf) %></b><br><small>Student Activity Fee</small></h4>
  <h4><b><%= number_to_currency(@school.budget, precision: 0) || "N/A" %></b><br><small>SGA Budget</small></h4>
  <h3 class="text-center">Student Government</h3>
  <div class="fa-row row">
    <div class="col-xs-4">
      <%= link_to @school.sga_website do %><i class="fa fa-globe"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to @school.sga_facebook do %><i class="fa fa-facebook"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to @school.sga_twitter do %><i class="fa fa-twitter"></i><% end %>
    </div>
  </div>
  <hr>
  <div class="fa-row row">
    <div class="col-xs-4">
      <%= link_to @school do %><i class="fa fa-bullseye"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to edit_school_path(@school) do %><i class="fa fa-cog"></i><% end %>
    </div>
    <div class="col-xs-4">
      <%= link_to @school, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-times-circle-o"></i><% end %>
    </div>
  </div>
  <br>
  <center><%= link_to "Paper", @school.newspaper, class: "btn btn-green btn-mini" %></center>
  <br>
  <h3 class="text-center">Competitor</h3>
  <h4><%= @school.competitor.name %></h4>
</div>

<% @school.people.each do |person| %>
  <div class="person_business_card">
    <h1 class="text-center"><%= person.full_name.titleize %></h1>
    <h5 class="text-center" title="<%= person.title %>"><%= truncate(person.title, length: 40) %></h5>
    <h4 class="text-center"><%= person.school.name %></h4>
    <hr>
    <div class="row text-center">
      <i class="fa fa-phone fa-2x"></i><br>
      <%= number_to_phone person.phone %><br>
    </div>
    <br>
    <div class="row text-center">
      <i class="fa  fa-envelope-o fa-2x"></i><br>
      <%= person.email %>
    </div>
    <hr>
    <legend>Social</legend>
    <div class="row fa-row">
      <div class="col-xs-4">
        <%= link_to person.facebook do %><i class="fa fa-facebook"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to person.twitter do %><i class="fa fa-twitter"></i><% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to person.linkedin do %><i class="fa fa-linkedin"></i><% end %>
      </div>
    </div>
    <div class="row fa-row">
      <div class="col-xs-4">
        <%= link_to person.school do %><i class="fa fa-book"></i> <% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to edit_person_path(person) do %><i class="fa fa-cog"></i> <% end %>
      </div>
      <div class="col-xs-4">
        <%= link_to person, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-times-circle-o"></i><% end %>
      </div>
    </div>
  </div>
  <% end %>