config/routes.rb
Kremlin::Application.routes.draw do

  resources :note_categories
  resources :notes
  resources :people
  resources :competitors
  resources :schools

  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :project_entries
  resources :projects

  resources :users do
    resources :projects do
      resources :project_entries
    end
    resources :notes
    resources :note_categories
  end

  root to: "pages#home"

end

app/models/note_category.rb
class NoteCategory < ActiveRecord::Base
  belongs_to :user
  has_many :notes
end

app/controllers/note_categories_controller.rb
class NoteCategoriesController < ApplicationController
  authorize_resource
  # GET /note_categories
  # GET /note_categories.json
  def index
    @user = User.find(params[:user_id])
    @note_categories = @user.note_categories.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @note_categories }
    end
  end

  # GET /note_categories/1
  # GET /note_categories/1.json
  def show
    @note_category = NoteCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note_category }
    end
  end

  # GET /note_categories/new
  # GET /note_categories/new.json
  def new
    @user = User.find(params[:user_id])
    @note_category = NoteCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note_category }
    end
  end

  # GET /note_categories/1/edit
  def edit
    @note_category = NoteCategory.find(params[:id])
  end

  # POST /note_categories
  # POST /note_categories.json
  def create
    @user = User.find(params[:user_id])
    @note_category = @user.note_categories.new(note_category_params)

    respond_to do |format|
      if @note_category.save
        format.html { redirect_to @note_category, notice: 'Note category was successfully created.' }
        format.json { render json: @note_category, status: :created, location: @note_category }
      else
        format.html { render action: "new" }
        format.json { render json: @note_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /note_categories/1
  # PUT /note_categories/1.json
  def update
    @user = current_user
    @note_category = NoteCategory.find(params[:id])

    respond_to do |format|
      if @note_category.update_attributes(note_category_params)
        format.html { redirect_to @note_category, notice: 'Note category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /note_categories/1
  # DELETE /note_categories/1.json
  def destroy
    @note_category = NoteCategory.find(params[:id])
    @note_category.destroy

    respond_to do |format|
      format.html { redirect_to note_categories_url }
      format.json { head :no_content }
    end
  end

  private

  def note_category_params
    params.require(:note_category)
          .permit(:name, :user_id)
  end
end

app/helpers/note_categories_helper.rb
module NoteCategoriesHelper
end

app/views/note_categories/_form.html.erb
<%= form_for [@user, @note_category] do |f| %>
  <% if @note_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note_category.errors.count, "error") %> prohibited this note_category from being saved:</h2>

      <ul>
      <% @note_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-red btn-mini" %>
  </div>
<% end %>

app/views/note_categories/edit.html.erb
<h1 class="text-center">Editing <%= @note_category.name %></h1>
<div class="formcontainer">
  <%= render 'form' %>
</div>

<%= link_to 'Show', @note_category %> |
<%= link_to 'Back', note_categories_path %>

app/views/note_categories/index.html.erb
<center><%= link_to new_user_note_category_path(current_user), class: "btn btn-red btn-mini" do %> <i class="fa fa-plus fa-3x"></i> <% end %></center>


<div class="container">
  <div class="note_category_container">
    <input type="text" class="" placeholder="Begin Typing" id="note_category_filter">
    <% @note_categories.each do |note_category| %>
        <h5 class="note_category_title" data-name="<%= note_category.name %>"><%= link_to note_category.name, note_category %></h5>
    <% end %>
  </div>
</div>

app/views/note_categories/new.html.erb
<h1 class="text-center">New Category</h1>
<div class="formcontainer">
  <%= render 'form' %>
</div>

app/views/note_categories/show.html.erb
<h1 class="text-center"><%= @note_category.name %></h1>
<h4 class="text-center"><%= @note_category.user.full_name.titleize %></h4>
<h5><center><%= link_to 'Edit', edit_user_note_category_path(current_user, @note_category), class: "text-center" %></center></h5>
<center><%= link_to new_user_note_path(current_user, note_category_id: @note_category.id), class: "btn btn-red" do %><i class="fa fa-plus fa-2x"></i> <% end %></center>

<div class="notes_container">
  <% if @note_category.notes.empty? %>
  <center>
  <i class="fa fa-frown-o fa-4x"></i>
  <h5>We used to dream about this stuff.<br>Now we get to build it.<br>It's pretty great.</h5>
  </center>
  <% end %>
  <% @note_category.notes.order(purchased: :asc).each do |note| %>
  <% if note.purchased? %>
  <h3><strike><%= link_to note.title, note.url, :target => "_blank" %></strike></h3>
  <% else %>
  <h3><%= link_to note.title, note.url, :target => "_blank" %></h3>
  <% end %>
  <h5><%= note.user.full_name.titleize %> &middot; <%= note.created_at.strftime("%D") %> at <%= note.created_at.strftime("%I:%M%P") %> &middot; <%= link_to "Edit", edit_user_note_path(current_user, note) %></h5>
  <p><%= note.thought %></p>
  <hr>
  <% end %>
</div>